TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += zfmagfld.db
DB += zfmagfld_axes.db

#=======================================
include $(TOP)/configure/RULES
